apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ewallet-ingress
  namespace: ewallet
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - shopacc.pro.vn
    secretName: shopacc-tls
  rules:
  - host: shopacc.pro.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-app
            port:
              number: 80
