apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: java-app
  namespaceSelector:
    matchNames:
      - ewallet
  endpoints:
    - port: http-80
      path: /actuator/prometheus
      interval: 15s
