apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ewallet

resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - mysql/pvc.yaml
  - redis/deployment.yaml
  - kafka/deployment.yaml
  - vault/deployment.yaml
  - ingress/main-ingress.yaml
  - ingress/monitoring-ingress.yaml

# Common labels applied to all resources
labels:
  - pairs:
      managed-by: kustomize
      environment: base
